const std = @import("std");
const Options = @import("../options.zig").Options;
const Bundle = @import("compiler").zig.ModuleBundle;
const Self = @This();
const marker = "// Generated by zxc.\n";

module_path: []const u8,
declaration_path: []const u8,
module_source: []const u8,
declarations: []const u8,
pub fn create(allocator: std.mem.Allocator, bundle: Bundle, options: Options) !?Self {
    if (options.host != .node) return null;
    if (bundle.runner != null) return error.UnsupportedNodeRunner;

    const output = options.output.?;

    if (!std.mem.endsWith(u8, output, ".node")) return error.NodeAddonExtensionRequired;

    const signature = bundle.signature orelse return error.MissingNodeSignature;
    const stem = output[0 .. output.len - ".node".len];
    const relative = try std.fmt.allocPrint(allocator, "./{s}", .{std.fs.path.basename(output)});
    const path_literal = try std.json.Stringify.valueAlloc(allocator, relative, .{});

    return .{
        .module_path = try std.fmt.allocPrint(allocator, "{s}.cjs", .{stem}),
        .declaration_path = try std.fmt.allocPrint(allocator, "{s}.d.cts", .{stem}),
        .module_source = try std.fmt.allocPrint(allocator, marker ++ "const binding = require({s});\n\nexports.execute = binding.execute;\nexports.executeAsync = (...args) => new Promise((resolve, reject) => binding.executeTask(...args, resolve, reject));\n", .{path_literal}),
        .declarations = try @import("napi_declarations").render(allocator, signature.types, signature.input, signature.output),
    };
}

pub fn check(self: Self, io: std.Io, allocator: std.mem.Allocator, options: Options) !void {
    for ([_][]const u8{ self.module_path, self.declaration_path }) |path| {
        const absolute = try std.fs.path.resolve(allocator, &.{path});

        if (options.assembly) |assembly| {
            const assembly_path = try std.fs.path.resolve(allocator, &.{assembly});

            if (std.mem.eql(u8, absolute, assembly_path)) return error.ConflictingOutputPaths;
        }

        const existing = std.Io.Dir.cwd().readFileAlloc(io, path, allocator, .unlimited) catch |err| switch (err) {
            error.FileNotFound => continue,
            else => return err,
        };

        defer allocator.free(existing);

        if (!std.mem.startsWith(u8, existing, marker)) return error.NodeBindingWouldOverwriteFile;
    }
}

pub fn stage(self: Self, io: std.Io, allocator: std.mem.Allocator, directory: []const u8) !void {
    try @import("../artifacts.zig").write(io, try std.fs.path.join(allocator, &.{ directory, std.fs.path.basename(self.module_path) }), self.module_source);
    try @import("../artifacts.zig").write(io, try std.fs.path.join(allocator, &.{ directory, std.fs.path.basename(self.declaration_path) }), self.declarations);
}

pub fn publish(self: Self, io: std.Io) !void {
    try @import("../artifacts.zig").write(io, self.module_path, self.module_source);
    try @import("../artifacts.zig").write(io, self.declaration_path, self.declarations);
}
