const std = @import("std");
const ast = @import("ast.zig");
const Allocator = std.mem.Allocator;

pub fn generate(allocator: Allocator, program: ast.Program) Allocator.Error![]u8 {
    var generator = Generator{
        .allocator = allocator,
    };

    defer generator.output.deinit(allocator);

    return generator.run(program);
}

const Generator = struct {
    allocator: Allocator,
    output: std.ArrayList(u8) = .empty,
    fn run(self: *Generator, program: ast.Program) Allocator.Error![]u8 {
        try self.write(
            \\// Generated by the zxc MVP compiler.
            \\// Do not edit this file directly.
            \\
        );

        for (program.declarations) |declaration| {
            try self.generateDeclaration(declaration);
            try self.write("\n");
        }

        try self.write("pub fn execute(in: Input) Output {\n");
        try self.generateStatements(program.function_declaration.body, 1);
        try self.write("}\n");

        return self.output.toOwnedSlice(self.allocator);
    }
    fn generateDeclaration(self: *Generator, declaration: ast.Declaration) Allocator.Error!void {
        switch (declaration) {
            .enum_decl => |value| {
                try self.output.print(self.allocator, "pub const {s} = enum {{\n", .{value.name});

                for (value.members) |member| {
                    try self.write("    ");
                    try self.write(member.name);
                    try self.write(",\n");
                }

                try self.write("};\n");
            },
            .type_decl => |value| {
                try self.output.print(self.allocator, "pub const {s} = ", .{value.name});
                try self.generateType(value.value_type, 0);
                try self.write(";\n");
            },
        }
    }

    fn generateType(
        self: *Generator,
        value_type: *const ast.TypeNode,
        indentation: usize,
    ) Allocator.Error!void {
        switch (value_type.*) {
            .named => |value| {
                if (std.mem.eql(u8, value.name, "string")) {
                    try self.write("[]const u8");
                } else {
                    try self.write(value.name);
                }
            },
            .optional => |inner| {
                try self.write("?");
                try self.generateType(inner, indentation);
            },
            .list => |item| {
                try self.write("[]const ");
                try self.generateType(item, indentation);
            },
            .object => |object| {
                try self.write("struct {\n");

                for (object.fields) |field| {
                    try self.writeIndent(indentation + 1);
                    try self.write(field.name);
                    try self.write(": ");
                    try self.generateType(field.value_type, indentation + 1);
                    if (isOptional(field.value_type)) try self.write(" = null");
                    try self.write(",\n");
                }

                try self.writeIndent(indentation);
                try self.write("}");
            },
        }
    }

    fn generateStatements(
        self: *Generator,
        statements: []const ast.Statement,
        indentation: usize,
    ) Allocator.Error!void {
        for (statements) |statement| {
            switch (statement) {
                .constant => |value| {
                    try self.writeIndent(indentation);
                    try self.write("const ");
                    try self.write(value.name);

                    if (inferredConstType(value.initializer)) |value_type| {
                        try self.write(": ");
                        try self.write(value_type);
                    }

                    try self.write(" = ");
                    try self.generateExpression(value.initializer, indentation);
                    try self.write(";\n");
                },
                .if_stmt => |value| {
                    try self.writeIndent(indentation);
                    try self.write("if (");
                    try self.generateExpression(value.condition, indentation);
                    try self.write(") {\n");
                    try self.generateStatements(value.then_body, indentation + 1);
                    try self.writeIndent(indentation);

                    if (value.else_body) |else_body| {
                        try self.write("} else {\n");
                        try self.generateStatements(else_body, indentation + 1);
                        try self.writeIndent(indentation);
                        try self.write("}\n");
                    } else {
                        try self.write("}\n");
                    }
                },
                .switch_stmt => |value| {
                    try self.writeIndent(indentation);
                    try self.write("switch (");
                    try self.generateExpression(value.subject, indentation);
                    try self.write(") {\n");

                    for (value.cases) |switch_case| {
                        try self.writeIndent(indentation + 1);

                        if (switch_case.value) |case_value| {
                            try self.generateExpression(case_value, indentation + 1);
                        } else {
                            try self.write("else");
                        }

                        if (switch_case.body.len == 0) {
                            try self.write(" => {},\n");

                            continue;
                        }

                        try self.write(" => {\n");
                        try self.generateStatements(switch_case.body, indentation + 2);
                        try self.writeIndent(indentation + 1);
                        try self.write("},\n");
                    }

                    try self.writeIndent(indentation);
                    try self.write("}\n");
                },
                .return_stmt => |value| {
                    try self.writeIndent(indentation);
                    try self.write("return");

                    if (value.value) |expression| {
                        try self.write(" ");
                        try self.generateExpression(expression, indentation);
                    }

                    try self.write(";\n");
                },
            }
        }
    }

    fn generateExpression(
        self: *Generator,
        expression: *const ast.Expression,
        indentation: usize,
    ) Allocator.Error!void {
        switch (expression.*) {
            .literal => |value| try self.write(value.source),
            .identifier => |value| try self.write(value.name),
            .member => |value| {
                try self.generateExpression(value.target, indentation);
                try self.write(".");
                try self.write(value.property);
            },
            .index => |value| {
                try self.generateExpression(value.target, indentation);
                try self.write("[");
                try self.generateExpression(value.index, indentation);
                try self.write("]");
            },
            .unary => |value| {
                try self.write("(");
                try self.write(value.operator);
                try self.generateExpression(value.operand, indentation);
                try self.write(")");
            },
            .binary => |value| {
                try self.write("(");
                try self.generateExpression(value.left, indentation);
                try self.write(" ");
                try self.write(zigOperator(value.operator));
                try self.write(" ");
                try self.generateExpression(value.right, indentation);
                try self.write(")");
            },
            .ternary => |value| {
                try self.write("(if (");
                try self.generateExpression(value.condition, indentation);
                try self.write(") ");
                try self.generateExpression(value.when_true, indentation);
                try self.write(" else ");
                try self.generateExpression(value.when_false, indentation);
                try self.write(")");
            },
            .object => |value| {
                if (value.fields.len == 0) {
                    try self.write(".{}");

                    return;
                }

                try self.write(".{\n");

                for (value.fields) |field| {
                    try self.writeIndent(indentation + 1);
                    try self.write(".");
                    try self.write(field.name);
                    try self.write(" = ");
                    try self.generateExpression(field.value, indentation + 1);
                    try self.write(",\n");
                }

                try self.writeIndent(indentation);
                try self.write("}");
            },
            .list => |value| {
                try self.write("&.{");

                for (value.items, 0..) |item, index| {
                    if (index > 0) try self.write(",");
                    try self.write(" ");
                    try self.generateExpression(item, indentation);
                }

                if (value.items.len > 0) try self.write(" ");
                try self.write("}");
            },
            .call => |value| {
                try self.generateExpression(value.callee, indentation);
                try self.write("(");

                for (value.arguments, 0..) |argument, index| {
                    if (index > 0) try self.write(", ");
                    try self.generateExpression(argument, indentation);
                }

                try self.write(")");
            },
        }
    }
    fn write(self: *Generator, value: []const u8) Allocator.Error!void {
        try self.output.appendSlice(self.allocator, value);
    }
    fn writeIndent(self: *Generator, indentation: usize) Allocator.Error!void {
        for (0..indentation) |_| try self.write("    ");
    }
};

fn isOptional(value_type: *const ast.TypeNode) bool {
    return switch (value_type.*) {
        .optional => true,
        else => false,
    };
}

fn zigOperator(operator: []const u8) []const u8 {
    if (std.mem.eql(u8, operator, "&&")) return "and";
    if (std.mem.eql(u8, operator, "||")) return "or";
    if (std.mem.eql(u8, operator, "??")) return "orelse";

    return operator;
}

fn inferredConstType(expression: *const ast.Expression) ?[]const u8 {
    return switch (expression.*) {
        .literal => |value| switch (value.kind) {
            .number => if (std.mem.indexOfScalar(u8, value.source, '.') == null) "u64" else "f64",
            .boolean => "bool",
            .string => "[]const u8",
            .null => null,
        },
        .unary => |value| if (std.mem.eql(u8, value.operator, "!")) "bool" else "i64",
        .binary => |value| if (isBooleanOperator(value.operator))
            "bool"
        else if (std.mem.eql(u8, value.operator, "??"))
            inferredConstType(value.right)
        else
            "u64",
        .ternary => |value| unifyInferredTypes(
            inferredConstType(value.when_true),
            inferredConstType(value.when_false),
        ),
        else => null,
    };
}

fn isBooleanOperator(operator: []const u8) bool {
    const operators = [_][]const u8{
        "&&", "||", "==", "!=", "<", "<=", ">", ">=",
    };

    for (operators) |candidate| {
        if (std.mem.eql(u8, operator, candidate)) return true;
    }

    return false;
}

fn unifyInferredTypes(left: ?[]const u8, right: ?[]const u8) ?[]const u8 {
    if (left == null) return right;
    if (right == null) return left;
    if (std.mem.eql(u8, left.?, right.?)) return left;

    return null;
}
