const ir = @import("../ir.zig");
const views = @import("views.zig");
const Original = @FieldType(ir.Expression, "value");

pub const Expression = struct {
    type_id: ir.TypeId,
    span: @import("../source.zig").Span,
    value: union(enum) {
        integer: @FieldType(Original, "integer"),
        negative_integer: @FieldType(Original, "negative_integer"),
        float: @FieldType(Original, "float"),
        string: @FieldType(Original, "string"),
        boolean: @FieldType(Original, "boolean"),
        none,
        unit,
        some: @FieldType(Original, "some"),
        capture: @FieldType(Original, "capture"),
        task: @FieldType(Original, "task"),
        await_task: @FieldType(Original, "await_task"),
        cancel_task: @FieldType(Original, "cancel_task"),
        parallel: views.ParallelBranches,
        optional_value: @FieldType(Original, "optional_value"),
        enum_value: @FieldType(Original, "enum_value"),
        error_value: @FieldType(Original, "error_value"),
        reference: @FieldType(Original, "reference"),
        store_get: @FieldType(Original, "store_get"),
        field: @FieldType(Original, "field"),
        index: @FieldType(Original, "index"),
        length: @FieldType(Original, "length"),
        list: @FieldType(Original, "list"),
        tuple: @FieldType(Original, "tuple"),
        tuple_field: @FieldType(Original, "tuple_field"),
        template: @FieldType(Original, "template"),
        list_operation: @FieldType(Original, "list_operation"),
        transform: @FieldType(Original, "transform"),
        scope: struct { bindings: views.Bindings, result: ir.ExprId },
        iteration: @FieldType(Original, "iteration"),
        list_update: @FieldType(Original, "list_update"),
        call: @FieldType(Original, "call"),
        unary: @FieldType(Original, "unary"),
        binary: @FieldType(Original, "binary"),
        conditional: @FieldType(Original, "conditional"),
        match_expr: struct { subject: ?ir.ExprId, arms: views.MatchArms, fallback: ir.ExprId },
        object: struct { fields: views.ObjectFields, evaluation: []const ir.ExprId },
    },
};
