// Generated by zxc.
import type { Buffer } from 'node:buffer'

type InputType1 = boolean
type InputType2 = number
type InputType7 = bigint
type InputType9 = number
type InputType10 = string
type InputType11 = 'Read' | 'Write'
type InputType12 = Uint8Array | Uint8ClampedArray | ReadonlyArray<number>
type InputType13 = readonly [InputType1, InputType9]
type InputType14 = InputType10 | null | undefined
type InputType15 = {
	bytes: InputType12
	count: InputType7
	mode: InputType11
	name: InputType10
	note?: InputType14
	pair: InputType13
}

type OutputType1 = boolean
type OutputType2 = number
type OutputType7 = bigint
type OutputType9 = number
type OutputType10 = string
type OutputType11 = 'Read' | 'Write'
type OutputType12 = Buffer
type OutputType13 = [OutputType1, OutputType9]
type OutputType14 = OutputType10 | null
type OutputType15 = {
	bytes: OutputType12
	count: OutputType7
	mode: OutputType11
	name: OutputType10
	note: OutputType14
	pair: OutputType13
}

export type Input = InputType15
export type Output = OutputType15

export function execute(input: Input): Output
