// Generated by zxc.
import type { Buffer } from 'node:buffer'

type InputType0 = void

type OutputType6 = number

export type Input = InputType0
export type Output = OutputType6

export function execute(): Output
