// Generated by zxc.
import type { Buffer } from 'node:buffer'

type InputType5 = bigint

type OutputType0 = void

export type Input = InputType5
export type Output = OutputType0

export function execute(input: Input): Output
