import json
from pathlib import Path


directory = Path(__file__).resolve().parent
reasons = {
    'builtin': '完整四项函数对象观察要求可扩展、[object Function]、Function.prototype原型及无own prototype；typed应用输出不提供此全局内建函数对象。',
    'length': 'JSON.stringify.length为3且descriptor为writable=false、enumerable=false、configurable=true；不能用应用参数数量替代内建函数反射。',
    'name': 'JSON.stringify.name为stringify并验证不可写、不可枚举、可配置descriptor；typed输出没有该函数对象反射契约。',
    'not-a-constructor': 'isConstructor为false且new JSON.stringify({})抛TypeError；普通应用入口不实现JS构造协议。',
    'prop-desc': 'JSON对象的stringify属性必须可写、不可枚举、可配置；没有对应JS全局对象descriptor。',
    'property-order': '数字key先排序，删除p1/p3后重建p1改变枚举顺序，getter新增extra不进入此次枚举；固定字段顺序不能替代动态枚举快照。',
    'replacer-array-abrupt': 'replacer的Proxy length getter、length的ToPrimitive以及索引getter分别抛Test262Error；不能删除第二参数或把它改为输入解析错误。',
    'replacer-array-duplicates': '重复key只读取value getter一次并输出key=true；固定对象输出不覆盖PropertyList去重与getter次数。',
    'replacer-array-empty': '空PropertyList使两个对象输出{}，数组保留元素并把其中对象输出{}；typed输出没有第二参数的递归筛选协议。',
    'replacer-array-number-object': '盒装Number(10)的ToString覆盖返回toString，valueOf不得调用，筛选输出toString字段；不能预先提供已转换key。',
    'replacer-array-number': 'replacer含-0、1、-4、0.3、-Infinity、NaN并按ToString筛选六个字符串key；与无replacer文本相等仍要求执行完整PropertyList协议。',
    'replacer-array-order': 'replacer c/b/a决定顶层及嵌套对象字段顺序；不能删除第二参数后用手排固定字段冒充。',
    'replacer-array-proxy-revoked-realm': '外realm的revoked数组Proxy用作replacer，必须抛当前realm TypeError；普通typed输出不提供realm或Proxy。',
    'replacer-array-proxy-revoked': 'revoked数组Proxy用作replacer必须在IsArray观察抛TypeError；拒绝某个JSON文本无法替代该协议。',
    'replacer-array-proxy': 'Proxy包裹[b]作为PropertyList，顶层和嵌套仅输出b字段；静态选择字段不会覆盖Proxy和第二参数。',
    'replacer-array-string-object': '盒装String的自定义toString返回toString且valueOf不得调用，筛选对应字段；typed string没有盒装转换协议。',
    'replacer-array-undefined': 'undefined、空洞和稀疏replacer必须忽略，只有中间key保留；普通列表不提供JS空洞及PropertyList生成。',
    'replacer-array-wrong-type': 'replacer中的bool/null/普通对象/Symbol均忽略，value Proxy除toJSON外不得被get；输出{}本身不足以证明这些观察。',
    'replacer-function-abrupt': 'replacer调用抛Test262Error；typed序列化没有JS回调第二参数。',
    'replacer-function-arguments': '八次回调检查holder身份、key、value和深度次序，toJSON结果也参与；相同JSON文本不能替代回调观察。',
    'replacer-function-array-circular': 'replacer把值替换为同一数组造成循环并抛TypeError；不能改成固定typed数组或忽略回调。',
    'replacer-function-object-circular': '直接及间接两种replacer返回祖先对象造成循环并抛TypeError；缺少动态引用身份及替换协议。',
    'replacer-function-object-deleted-property': 'getter a删除b，但枚举快照仍对b调用replacer且value为undefined，再输出替换字符串；静态字段无法保留删除和访问次序。',
    'replacer-function-result-undefined': '顶层undefined结果、数组元素null、对象字段省略和嵌套组合全部来自replacer；不能预先构造最终值删除回调。',
    'replacer-function-result': '从null开始，逐次断言回调value为null并生成嵌套object/array/bool/string；固定输出会删除完整动态替换过程。',
    'replacer-function-tojson': 'toJSON先执行，replacer随后处理字符串或修改返回对象，结果带toJSON|replacer；不能删除执行顺序。',
    'replacer-function-wrapper': 'replacer的this wrapper具有Object.prototype、唯一空key及完整descriptor，且创建不得触发原型setter；不是普通对象值比较。',
    'replacer-wrong-type': '八种不合法第二参数必须正确忽略，包括盒装对象与Symbol；应用输出无此参数，直接删参数不能登记整份。',
    'space-number-float': '第三参数数值向整数截断，含负数及盒装5.11111；应用紧凑JSON无可传入的JS space转换契约。',
    'space-number-object': '盒装Number按valueOf转换缩进，toString不得调用，并验证转换异常；不能换成固定缩进选项。',
    'space-number-range': '盒装负数缩进归0且100限制为10；没有JS第三参数的范围与盒装协议。',
    'space-number': 'space=0等同空字符串，space=4等同四个空格，涉及完整嵌套对象；普通输出无第三参数。',
    'space-string-object': '盒装String按toString转换xxx/---，valueOf不得调用，并传播转换异常；普通UTF-8 string不是此对象协议。',
    'space-string-range': '缩进字符串0123456789xxxxxxxxx按前十个code units截断；没有可输入的第三参数或对应JS截断协议。',
    'space-string': '空space等同省略，两个空格space要求逐行精确嵌套缩进；紧凑JSON协议不提供JS space参数。',
    'space-wrong-type': 'null、bool、盒装Boolean、Symbol和普通对象第三参数必须忽略；无space参数不能当作已执行这些类型检查。',
    'value-array-abrupt': '数组Proxy length getter、ToLength转换及索引getter三条异常路径，包含嵌套数组/对象；typed数组无此动态访问协议。',
    'value-array-circular': '直接与间接数组引用循环抛TypeError；typed JSON值不能表达这些JS引用身份。',
    'value-array-proxy-revoked': '顶层和三层嵌套revoked数组Proxy都抛TypeError；typed列表不提供撤销Proxy语义。',
    'value-array-proxy': 'Proxy getter动态提供length=2与索引值，包含Proxy套Proxy和嵌套数组；提供[0,1]不能覆盖访问协议。',
    'value-bigint-cross-realm': '跨realm盒装BigInt先抛TypeError，修改外realm原型toJSON后输出字符串100；静态整数输出没有realm/原型协议。',
    'value-bigint-order': 'BigInt.prototype.toJSON必须先于replacer，分别返回primitive/盒装BigInt后抛TypeError，并断言step=2；不能仅测试大整数范围。',
    'value-bigint-replacer': '顶层与对象内BigInt经过replacer转换字符串bigint；缺少JS回调、typeof bigint和动态替换协议。',
    'value-bigint-tojson-receiver': '先验证BigInt拒绝，再用严格getter观察toJSON receiver为primitive bigint；静态整数没有原型getter receiver。',
    'value-bigint-tojson': '修改BigInt.prototype.toJSON后把0n转换为字符串0；typed大整数与JS原型方法不同。',
    'value-bigint': 'primitive 0n、Object(0n)和对象内0n均抛TypeError；静态有界整数既不是JS BigInt也不提供盒装内部slot。',
    'value-boolean-object': '盒装Boolean直接输出、toJSON返回盒装false以及replacer返回盒装true共三条路径；仅测试bool会删除盒装及回调观察。',
    'value-function': '函数顶层返回undefined，数组位置变null，对象字段省略；普通void/null不能保留JS函数值的上下文协议。',
    'value-number-negative-zero': '完整三个精确文本观察可由f64标量、tuple和固定key对象表达。实际三目标输出-0、["-0",0,-0]、{"key":-0}，原文要求0、["-0",0,0]、{"key":0}；这是合法JSON的明确文本契约差异，不能笼统归为动态JS或解析后宣布通过。',
    'value-number-non-finite': '完整三个观察可由普通f64运算与容器表达。实际三目标均按NonFiniteJsonNumber拒绝Infinity、对象-Infinity、数组NaN，原文要求null、{"key":null}、[null]；这是已修复合法JSON边界后的明确输出政策差异，不可改原文预期为错误后登记通过。',
    'value-number-object': '盒装Number直接输出8.5，replacer返回盒装数按valueOf得到2，toJSON返回对象的转换异常传播；f64恒等应用无法保留内部slot和ToPrimitive。',
    'value-object-abrupt': '对象key getter抛Test262Error，必须在序列化访问中传播；静态字段无getter。',
    'value-object-circular': '直接自引用及getter返回祖先的间接对象循环均抛TypeError；typed对象不能表达动态引用循环。',
    'value-object-proxy-revoked': '顶层和两层对象内revoked Proxy均抛TypeError；普通typed对象不提供Proxy撤销观察。',
    'value-object-proxy': 'ownKeys、getOwnPropertyDescriptor和get trap动态制造a/b字段，包含嵌套及Proxy套Proxy；固定a/b字段不能证明trap协议。',
    'value-primitive-top-level': '完整六次观察包括undefined返回undefined；前五个null/bool/string/number可表达，但应用void输出null，不能删除第六项登记整份。',
    'value-string-escape-ascii': '完整35项断言同时验证含quote/backslash/00..1f的动态属性名和value，各escape出现四次并精确比整串；ZX对象字段只允许Identifier，单测字符串值会删除key观察。',
    'value-string-escape-unicode': '完整12次UTF-16观察中10次含孤立surrogate，只有两次全为有效pair；UTF-8契约不能保留孤立code unit，替换字符或只选两次会改变原文。',
    'value-string-object': '盒装String直接输出、toJSON返回对象按自定义toString转换、replacer返回对象的转换异常共三条路径；普通string没有盒装转换协议。',
    'value-symbol': 'Symbol顶层undefined、数组null、对象字段省略，且Symbol key忽略；typed字符串和普通字段无法保留Symbol身份。',
    'value-tojson-abrupt': '读取toJSON getter与调用toJSON方法分别抛Test262Error；不能改成JSON文本拒绝。',
    'value-tojson-arguments': '三种位置观察toJSON调用次数、this身份、空key/索引1/key参数，以及undefined/null/字段省略结果；普通输出不能省略这些回调观察。',
    'value-tojson-array-circular': '数组toJSON返回包含自身的祖先数组造成TypeError；需要方法调用与引用身份。',
    'value-tojson-not-function': 'null/bool/array/RegExp四种非callable toJSON值必须作为普通字段输出，其中RegExp变{}；不能删除RegExp或无调用类型判定。',
    'value-tojson-object-circular': '对象toJSON返回包含自身的祖先对象造成TypeError；typed对象无该动态替换与引用身份。',
    'value-tojson-result': 'toJSON分别返回数组、undefined、null和对象，涉及数组、盒装String/Number及不同输出位置；静态最终值不能覆盖调用及结果转换。',
}
entries = [json.loads(line) for line in (directory / '待审文件.jsonl').read_text().splitlines()]
assert {Path(row['path']).stem for row in entries} == set(reasons)
rows = [{
    'path': row['path'],
    'sha256': row['sha256'],
    'status': 'excluded',
    'reason': reasons[Path(row['path']).stem] + ' 当前完整文件不适配，不声称JS兼容通过。',
    'contract': 'packages/cli/README.md 默认typed JSON输出；packages/genz/src/host/json_output.zig 非有限输出政策；packages/compiler/src/zx/frontend/parser/types/field.zx 静态字段；docs/2026-10-06/JSON字符串化完整原文审阅计划.md',
    'cases': [],
} for row in entries]
target = directory / '草稿/packages/test/upstream/reviews/built_ins/json/stringify.jsonl'
target.parent.mkdir(parents=True, exist_ok=True)
target.write_text(''.join(json.dumps(row, ensure_ascii=False, separators=(',', ':')) + '\n' for row in rows))
print('66 individually justified complete-file reviews; zero claimed executable adaptations')
