const std = @import("std");
const ir = @import("zx").ir;

pub fn render(allocator: std.mem.Allocator, types: []const ir.Type, input: ir.TypeId, output: ir.TypeId) std.mem.Allocator.Error![]u8 {
    var text: std.Io.Writer.Allocating = .init(allocator);

    errdefer text.deinit();

    const seen = try allocator.alloc(bool, types.len);

    defer allocator.free(seen);
    write(&text.writer, types, input, output, seen) catch return error.OutOfMemory;

    return text.toOwnedSlice();
}

fn write(writer: *std.Io.Writer, types: []const ir.Type, input: ir.TypeId, output: ir.TypeId, seen: []bool) std.Io.Writer.Error!void {
    try writer.writeAll("// Generated by zxc.\nimport type { Buffer } from \"node:buffer\";\n\n");

    for ([_]ir.TypeId{ input, output }, [_]bool{ true, false }) |root, incoming| {
        @memset(seen, false);
        mark(types, root, seen);

        for (types, 0..) |value, index| {
            if (!seen[index]) continue;
            try writer.print("type {s}{d} = ", .{ prefix(incoming), index });
            try definition(writer, types, value, incoming);
            try writer.writeAll(";\n");
        }

        try writer.writeByte('\n');
    }

    try writer.print("export type Input = InputType{d};\nexport type Output = OutputType{d};\n\n", .{ @intFromEnum(input), @intFromEnum(output) });
    try writer.writeAll(if (types[@intFromEnum(input)] == .scalar and types[@intFromEnum(input)].scalar == .void) "export function execute(): Output;\n" else "export function execute(input: Input): Output;\n");
}

fn mark(types: []const ir.Type, id: ir.TypeId, seen: []bool) void {
    const index = @intFromEnum(id);

    if (seen[index]) return;

    seen[index] = true;

    switch (types[index]) {
        .optional, .list => |child| mark(types, child, seen),
        .tuple => |children| for (children) |child| mark(types, child, seen),
        .object => |fields| for (fields) |field| mark(types, field.type_id, seen),
        else => {},
    }
}

fn definition(writer: *std.Io.Writer, types: []const ir.Type, value: ir.Type, incoming: bool) std.Io.Writer.Error!void {
    const name = prefix(incoming);

    switch (value) {
        .scalar => |scalar| try writer.writeAll(switch (scalar) {
            .void => "void",
            .bool => "boolean",
            .u64, .i64 => "bigint",
            .string => "string",
            else => "number",
        }),
        .optional => |child| try writer.print("{s}{d} | null{s}", .{ name, @intFromEnum(child), if (incoming) " | undefined" else "" }),
        .list => |child| {
            if (types[@intFromEnum(child)] == .scalar and types[@intFromEnum(child)].scalar == .u8) {
                try writer.writeAll(if (incoming) "Uint8Array | Uint8ClampedArray | ReadonlyArray<number>" else "Buffer");
            } else try writer.print("{s}<{s}{d}>", .{ if (incoming) "ReadonlyArray" else "Array", name, @intFromEnum(child) });
        },
        .tuple => |children| {
            try writer.writeAll(if (incoming) "readonly [" else "[");

            for (children, 0..) |child, index| {
                if (index != 0) try writer.writeAll(", ");
                try writer.print("{s}{d}", .{ name, @intFromEnum(child) });
            }

            try writer.writeByte(']');
        },
        .object => |fields| {
            try writer.writeAll("{\n");

            for (fields) |field| {
                try writer.writeAll("  ");
                try std.json.Stringify.value(field.name, .{}, writer);
                try writer.print("{s}: {s}{d};\n", .{ if (incoming and types[@intFromEnum(field.type_id)] == .optional) "?" else "", name, @intFromEnum(field.type_id) });
            }

            try writer.writeByte('}');
        },
        .enumeration => |enumeration| for (enumeration.members, 0..) |member, index| {
            if (index != 0) try writer.writeAll(" | ");
            try std.json.Stringify.value(member, .{}, writer);
        },
    }
}

fn prefix(incoming: bool) []const u8 {
    return if (incoming) "InputType" else "OutputType";
}
