from pathlib import Path
import hashlib
import json
import re
import subprocess


doc = Path(__file__).resolve().parent
baseline = json.loads((doc / "执行输入.json").read_text())
root = Path(baseline["root"])
run = Path(baseline["run"])
sha = lambda data: hashlib.sha256(data).hexdigest()
assert subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=root, text=True).strip() == baseline["source_commit"]

for path, identity in baseline["inputs"].items():
    assert sha((root / path).read_bytes()) == identity, path
    assert sha((Path(baseline["snapshot"]) / path).read_bytes()) == identity, path

for group in ["toolchain_inputs", "external_inputs"]:
    for path, identity in baseline.get(group, {}).items():
        assert sha(Path(path).read_bytes()) == identity, path

for path in baseline["formal_files"]:
    assert (doc / "草稿" / path).read_bytes() == (root / path).read_bytes(), path

programs = json.loads((doc / "生成记录.json").read_text())
assert {item["method"] for item in programs} == {"map", "filter", "every", "some"}
assert len(programs) == 4

for label, binary in [("helper", "compile-fixtures"), ("helper-ReleaseSafe", "compile-fixtures-ReleaseSafe")]:
    state = json.loads((run / (label + "-state.json")).read_text())
    assert state["status"] == "terminal" and state["compile_exit"] == state["execute_exit"] == state["signature_exit"] == 0
    assert sha((run / binary).read_bytes()) == state["binary_sha256"]
    raw = (run / (label + ".txt")).read_bytes()
    assert sha(raw) == state["log_sha256"]
    assert (doc / "编译证据" / (label + ".txt")).read_bytes() == raw
    frames = {}

    for piece in raw.split(b"\x1e")[1:]:
        name, separator, rest = piece.partition(b"\x1f")
        source, end, _ = rest.partition(b"\x1d")
        assert separator and end
        frames[name.decode().removesuffix(".zx")] = source

    assert len(frames) == 4

    for item in programs:
        assert frames[item["method"]] == Path(item["source_path"]).read_bytes()

total = 0

for mode in ["Debug", "ReleaseSafe"]:
    evidence = json.loads((doc / (mode + "完整证据.json")).read_text())
    assert evidence["status"] == "terminal" and evidence["exit_code"] == 0
    assert len(evidence["executions"]) == 4

    for item, execution in zip(programs, evidence["executions"]):
        assert item["method"] == execution["method"]
        assert execution["compile_exit"] == execution["signature_exit"] == execution["exit_code"] == 0
        assert sha(Path(execution["binary"]).read_bytes()) == execution["binary_sha256"]
        raw = (doc / execution["saved_log"]).read_bytes()
        assert sha(raw) == execution["log_sha256"]
        names = [match[1] for line in raw.decode().split("\n") if (match := re.fullmatch(r"\d+/20 .*\.test\.(.+)\.\.\.OK", line))]
        assert names == item["names"] and len(names) == 20
        assert b"All 20 tests passed." in raw
        assert sha(Path(item["source_path"]).read_bytes()) == item["source_sha256"]
        assert (doc / "生成源码" / (item["method"] + ".zig.txt")).read_bytes() == Path(item["source_path"]).read_bytes()
        assert sha(Path(item["test_path"]).read_bytes()) == item["test_sha256"]
        catalog = [json.loads(line) for line in Path(item["catalog_path"]).read_text().split("\n") if line]
        assert [row["id"] for row in catalog] == names
        total += len(names)

assert total == 160
originals = json.loads((doc / "原文身份.json").read_text())
original_runs = json.loads((doc / "原文执行证据.json").read_text())["records"]
assert len(originals) == 4 and len(original_runs) == 8
assert sum(len(record["observed"]) for record in original_runs) == 8

for original in originals:
    assert sha((doc / original["saved"]).read_bytes()) == original["sha256"]
    assert len([record for record in original_runs if record["path"] == original["path"] and record["sha256"] == original["sha256"]]) == 2

for path in doc.rglob("*.md"):
    assert len(path.read_text().split("\n")) <= 1000, path

print("PASS: 80 new cases, 160 actual checks, eight binaries, two public compiler drivers and matching generated bytes")
