from pathlib import Path
import json
keys=['title','tagline','description','experimental','readDocs','plainText','index','fullReference','twoFiles','rx','rxDescription','zx','zxDescription','runtimeNote','contract','identity','identityDescription','dependencies','dependenciesDescription','data','dataDescription','verification','verificationDescription','readNext','boundaries','boundariesDescription','capabilities']
values={
'en':['A language for agents.','Code should carry its architecture.','RX makes the flow explicit. ZX keeps business logic small and statically checkable. The compiler gives generated code a structure that can be read, checked, and changed.','experimental','read the docs','Plain text','index','full reference','Two files. Clear responsibilities.','.rx / orchestration','Declare modules, wire inputs and outputs, make dependencies visible.','.zx / computation','One responsibility. Explicit types. Constrained, verifiable logic.','RX shows the composition contract. Execution requires a host runtime; the production RX scheduler is not implemented.','The contract','Identity','A module is its file path.','Dependencies','Explicit. Directed. Acyclic.','Data','Named inputs, outputs, and state ownership.','Verification','Static checks first. Report actual execution separately.','Read only what you need','Small surface. Honest boundaries.','The ZX compiler emits Zig. RX supports module registration and dependency checks. A production RX runtime and database are not implemented.','Current capabilities'],
'zh':['为 Agent 设计的语言。','代码应当表达它的架构。','RX 明确描述流程，ZX 将业务逻辑限制在可静态验证的小单元中。编译器为生成的代码提供可阅读、可检查、可迭代的结构。','实验阶段','阅读文档','纯文本','索引','完整参考','两种文件，清晰分工。','.rx / 编排','声明模块，连接输入与输出，让依赖关系清晰可见。','.zx / 计算','单一职责、显式类型、受约束且可验证的逻辑。','RX 展示模块组合契约。执行需要宿主运行时；生产级 RX 调度器尚未实现。','核心契约','身份','模块的文件路径就是它的身份。','依赖','显式、有向、无环。','数据','明确命名的输入、输出与状态所有权。','验证','先执行静态检查，再单独报告实际执行结果。','只读你需要的内容','精简的能力范围，明确的边界。','ZX 编译器生成 Zig。RX 支持模块注册与依赖检查。生产级 RX 运行时和数据库尚未实现。','当前能力'],
'ja':['エージェントのための言語。','コード自体でアーキテクチャを表現する。','RX は処理の流れを明示し、ZX はビジネスロジックを静的に検証できる小さな単位に保ちます。コンパイラが、生成されたコードに読み取り・検証・変更できる構造を与えます。','実験段階','ドキュメントを読む','プレーンテキスト','索引','完全版リファレンス','2 種類のファイル。明確な役割。','.rx / オーケストレーション','モジュールを宣言し、入出力をつなぎ、依存関係を明示します。','.zx / 計算','単一の責務。明示的な型。制約があり、検証できるロジック。','RX はモジュールの合成契約を示します。実行にはホストランタイムが必要です。本番用の RX スケジューラは未実装です。','基本契約','識別子','モジュールはファイルパスで識別します。','依存関係','明示的で、有向かつ非循環。','データ','名前付きの入出力と明確な状態の所有権。','検証','静的検査を先に行い、実際の実行結果は分けて報告します。','必要な情報だけを読む','小さな機能範囲。明確な境界。','ZX コンパイラは Zig を生成します。RX はモジュール登録と依存関係の検査を提供します。本番用 RX ランタイムとデータベースは未実装です。','現在の対応範囲'],
'ko':['에이전트를 위한 언어.','코드 자체가 아키텍처를 표현해야 합니다.','RX는 흐름을 명시하고, ZX는 비즈니스 로직을 정적으로 검증할 수 있는 작은 단위로 유지합니다. 컴파일러는 생성된 코드에 읽고, 검증하고, 변경할 수 있는 구조를 부여합니다.','실험 단계','문서 읽기','일반 텍스트','색인','전체 참고 문서','두 가지 파일. 명확한 역할.','.rx / 오케스트레이션','모듈을 선언하고 입출력을 연결하여 의존 관계를 드러냅니다.','.zx / 계산','단일 책임, 명시적 타입, 제약이 있고 검증 가능한 로직.','RX는 모듈 구성 계약을 보여 줍니다. 실행에는 호스트 런타임이 필요하며, 프로덕션 RX 스케줄러는 아직 구현되지 않았습니다.','핵심 계약','식별자','모듈은 파일 경로로 식별합니다.','의존성','명시적이며, 방향이 있고, 순환하지 않습니다.','데이터','이름이 있는 입출력과 명확한 상태 소유권.','검증','정적 검사를 먼저 수행하고 실제 실행 결과는 별도로 보고합니다.','필요한 내용만 읽기','작은 기능 범위. 명확한 경계.','ZX 컴파일러는 Zig를 생성합니다. RX는 모듈 등록과 의존성 검사를 지원합니다. 프로덕션 RX 런타임과 데이터베이스는 아직 구현되지 않았습니다.','현재 지원 범위']}
site_keys=['docs','forAgents','source','skip','mainNavigation','footerNavigation','madeForAgents','notFound','returnDocs','documentation','plainText','rawLabel','fullText']
site_values={
'en':['Docs','For agents','GitHub','Skip to content','Main navigation','Footer navigation','made for agents','No document here.','Return to documentation','Documentation','plain text','Read {title} as Markdown','full text'],
'zh':['文档','面向 Agent','GitHub','跳至内容','主导航','页脚导航','为 Agent 而造','这里没有文档。','返回文档','文档','纯文本','以 Markdown 阅读「{title}」','完整文本'],
'ja':['ドキュメント','エージェント向け','GitHub','本文へ移動','メインナビゲーション','フッターナビゲーション','エージェントのために','ドキュメントが見つかりません。','ドキュメントに戻る','ドキュメント','プレーンテキスト','「{title}」を Markdown で読む','全文'],
'ko':['문서','에이전트용','GitHub','본문으로 이동','주 탐색','푸터 탐색','에이전트를 위해','문서를 찾을 수 없습니다.','문서로 돌아가기','문서','일반 텍스트','{title} 문서를 Markdown으로 읽기','전체 텍스트']}
ids=['overview','build-with-agents','getting-started','compose-modules','write-logic','keep-dependencies-acyclic','validate-and-deliver','language-reference','capabilities']
titles={
'en':['Overview','Build with agents','Get started','Compose RX modules','Write ZX logic','Keep dependencies acyclic','Validate and deliver','Language reference','Capabilities & limits'],
'zh':['概览','与 Agent 一起开发','开始使用','组合 RX 模块','编写 ZX 逻辑','保持依赖无环','验证与交付','语言参考','能力与限制'],
'ja':['概要','エージェントと開発する','はじめに','RX モジュールを組み合わせる','ZX ロジックを書く','依存関係を非循環に保つ','検証と引き渡し','言語リファレンス','対応範囲と制限'],
'ko':['개요','에이전트와 개발하기','시작하기','RX 모듈 구성하기','ZX 로직 작성하기','순환 의존성 방지','검증과 전달','언어 참고 문서','지원 범위와 제한']}
groups={'en':['Start here','Guides','Reference'],'zh':['从这里开始','指南','参考'],'ja':['ここから始める','ガイド','リファレンス'],'ko':['먼저 읽기','가이드','참고 자료']}
copy={
'en':['copy agent prompt','copied','copy unavailable — open plain text','Use zxc for this task. Read {url} first. Confirm the available compiler and host runtime capabilities. Separate RX orchestration from ZX logic, keep dependencies acyclic, and report only checks you actually ran. Ask for the business goal and expected inputs and outputs if they are missing.'],
'zh':['复制 Agent 提示词','已复制','无法复制，请打开纯文本','请使用 zxc 完成本任务。先阅读 {url}，确认可用的编译器与宿主运行时能力。分离 RX 编排与 ZX 逻辑，保持依赖无环，只报告实际执行过的验证。若缺少业务目标或预期输入输出，请先询问。'],
'ja':['エージェント用プロンプトをコピー','コピーしました','コピーできません。プレーンテキストを開いてください','このタスクには zxc を使用してください。まず {url} を読み、利用できるコンパイラとホストランタイムの機能を確認してください。RX のオーケストレーションと ZX のロジックを分離し、依存関係を非循環に保ってください。実際に行った検証のみを報告し、業務目標や期待する入出力が不明な場合は確認してください。'],
'ko':['에이전트 프롬프트 복사','복사됨','복사할 수 없습니다. 일반 텍스트를 여세요','이 작업에 zxc를 사용하세요. 먼저 {url} 문서를 읽고 사용 가능한 컴파일러와 호스트 런타임 기능을 확인하세요. RX 오케스트레이션과 ZX 로직을 분리하고 순환 의존성을 방지하세요. 실제 수행한 검증만 보고하고, 비즈니스 목표나 예상 입출력이 없으면 먼저 질문하세요.']}
agent={
'en':['A language and compiler for agents. Experimental.','Read capabilities before generating code. RX orchestration and ZX computation have different implementation boundaries. Links are relative to this origin.','Complete reference','Full documentation','HTML documentation','zxc — agent documentation','Document not found'],
'zh':['为 Agent 设计的语言与编译器，目前处于实验阶段。','生成代码前先阅读能力边界。RX 编排与 ZX 计算的实现范围不同。链接相对于当前站点。','完整参考','完整文档','HTML 文档','zxc — Agent 文档','未找到文档'],
'ja':['エージェント向けの言語とコンパイラ。実験段階です。','コードを生成する前に対応範囲を確認してください。RX のオーケストレーションと ZX の計算では、実装済みの範囲が異なります。リンクはこのサイトからの相対パスです。','完全版リファレンス','全文ドキュメント','HTML ドキュメント','zxc — エージェント向けドキュメント','ドキュメントが見つかりません'],
'ko':['에이전트를 위한 언어와 컴파일러입니다. 실험 단계입니다.','코드를 생성하기 전에 지원 범위를 읽으세요. RX 오케스트레이션과 ZX 계산은 구현 범위가 다릅니다. 링크는 현재 사이트 기준의 상대 경로입니다.','전체 참고 자료','전체 문서','HTML 문서','zxc — 에이전트 문서','문서를 찾을 수 없습니다']}
for locale in values:
 data={'home':dict(zip(keys,values[locale])),'site':dict(zip(site_keys,site_values[locale])),'docs':dict(zip(ids,titles[locale])),'groups':dict(zip(['start','guides','reference'],groups[locale])),'copy':dict(zip(['idle','success','error','prompt'],copy[locale])),'agent':dict(zip(['summary','intro','complete','full','html','title','notFound'],agent[locale]))}
 Path('packages/website/locales/'+locale+'.json').write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n')
